import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
const root=path.resolve(import.meta.dirname,'..');
const sections=['Start Here','Alerts & Communication','Evacuation & Shelter','Water, Food & Cooking','Home & Utilities','Hands-On Skills','Hazard Guides','Plans & Records'];
const statuses=['draft','under-review','approved'];
const required=['code','title','section','sectionNumber','status','version','lastReviewed','pageCount','reviewers','sources'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pdfEsc=s=>String(s).replace(/[^\x20-\x7e]/g,c=>c==='☐'?'[ ]':'-').replace(/([\\()])/g,'\\$1');
const xmlEsc=esc;
async function walk(d){return (await Promise.all((await fs.readdir(d,{withFileTypes:true})).map(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]))).flat()}
function parseScalar(v){v=v.trim();if(/^\d+$/.test(v))return Number(v);return v.replace(/^['"]|['"]$/g,'')}
function frontMatter(raw,file){const match=raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);if(!match)throw Error(`${file}: missing YAML front matter`);const data={};let parent=null;for(const line of match[1].split('\n')){if(!line.trim())continue;const list=line.match(/^\s+-\s+(.*)$/);if(list){if(!Array.isArray(data[parent]))data[parent]=[];data[parent].push(parseScalar(list[1]));continue}const kv=line.match(/^(\s*)([\w]+):\s*(.*)$/);if(!kv)throw Error(`${file}: unsupported metadata line: ${line}`);const [,indent,key,value]=kv;if(indent){if(!parent||Array.isArray(data[parent]))throw Error(`${file}: invalid nested metadata`);data[parent][key]=parseScalar(value)}else{parent=key;data[key]=value?parseScalar(value):key==='reviewers'?{}:[]}}return{data,content:match[2]}}
function inline(s){return s.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>')}
function markdown(src){let out='',list=null;for(const raw of src.split('\n')){const s=raw.trim();if(!s){if(list){out+=`</${list}>`;list=null}continue}if(s.startsWith('<')||s.startsWith('</')){out+=raw+'\n';continue}const h=s.match(/^(#{2,3})\s+(.*)$/);if(h){if(list){out+=`</${list}>`;list=null}const n=h[1].length;out+=`<h${n}>${inline(h[2])}</h${n}>`;continue}const li=s.match(/^[-*]\s+(.*)$/);if(li){if(list!=='ul'){if(list)out+=`</${list}>`;out+='<ul>';list='ul'}out+=`<li>${inline(li[1])}</li>`;continue}out+=`<p>${inline(s)}</p>`}if(list)out+=`</${list}>`;return out}
function plainBlocks(src){const cleaned=src.replace(/<!--.*?-->/gs,'').replace(/<br\s*\/?>/gi,'\n').replace(/<\/li>/gi,'\n').replace(/<\/p>|<\/div>|<\/h\d>|<\/ol>|<\/ul>/gi,'\n').replace(/<[^>]+>/g,'').replace(/\*\*/g,'').replace(/&mdash;/g,'-').replace(/&amp;/g,'&');return cleaned.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>({text:x.replace(/^#+\s*/,''),heading:/^##/.test(x),bullet:/^<li>|^[-*]\s/.test(x)}))}
function wrap(text,max){const words=text.split(/\s+/);const lines=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){lines.push(line);line=w}else line=(line+' '+w).trim()}if(line)lines.push(line);return lines}
function pageCommands(doc,src,index){const front=index===0,left=front?62:43,right=front?43:62,width=612-left-right-18;let y=747;const cmd=['1 1 1 rg 0 0 612 792 re f','0.125 0.17 0.20 rg'];const edgeX=front?579:12;cmd.push(`0.65 0.27 0.09 rg ${edgeX} 34 21 724 re f`);cmd.push(`BT /F2 8 Tf 1 0 0 1 ${left} 758 Tm 0.65 0.27 0.09 rg (${pdfEsc('LA HABRA HEIGHTS FIRE WATCH · EMERGENCY PREPAREDNESS BINDER')}) Tj ET`);cmd.push(`BT /F2 8 Tf 0 1 -1 0 ${front?594:27} 180 Tm 1 1 1 rg (${pdfEsc(doc.section.toUpperCase()+' · '+String(doc.sectionNumber).padStart(2,'0'))}) Tj ET`);cmd.push(`BT /F1 22 Tf 1 0 0 1 ${left} ${y} Tm 0.125 0.17 0.20 rg (${pdfEsc(index?doc.title+' - continued':doc.title)}) Tj ET`);y-=34;for(const b of plainBlocks(src)){const heading=/^##/.test(b.text)||/^(Before|Details|Prepare|Sample placement|Check the work|Reassess|Sources)/.test(b.text);const text=b.text.replace(/^#{1,6}\s*/,'').replace(/^[-*]\s*/, '- ');const size=heading?11:9.5,max=Math.floor(width/(size*.52));if(heading)y-=5;for(const line of wrap(text,max)){if(y<58)throw Error(`${doc.code} page ${index+1}: content overflow`);cmd.push(`BT /${heading?'F2':'F1'} ${size} Tf 1 0 0 1 ${left} ${y} Tm 0.125 0.17 0.20 rg (${pdfEsc(line)}) Tj ET`);y-=heading?15:12}y-=heading?2:3}cmd.push(`0.68 0.72 0.74 RG ${left} 39 m ${612-right-18} 39 l S`);cmd.push(`BT /F1 7.5 Tf 1 0 0 1 ${left} 27 Tm 0.32 0.38 0.41 rg (${pdfEsc(doc.code+' · v'+doc.version+' · '+doc.status.toUpperCase())}) Tj ET`);cmd.push(`BT /F1 7.5 Tf 1 0 0 1 ${612-right-150} 27 Tm (${pdfEsc('Reviewed '+doc.lastReviewed+' · '+(index+1)+' of '+doc.pageCount)}) Tj ET`);return cmd.join('\n')}
function makePdf(doc,chunks){const objs=[];const add=s=>(objs.push(s),objs.length);const font1=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'),font2=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');const contents=chunks.map((c,i)=>{const stream=pageCommands(doc,c,i);return add(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`)});const pagesObj=objs.length+chunks.length+1;const pageObjs=contents.map(content=>add(`<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${content} 0 R >>`));add(`<< /Type /Pages /Kids [${pageObjs.map(n=>n+' 0 R').join(' ')}] /Count ${pageObjs.length} >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesObj} 0 R >>`);let pdf='%PDF-1.4\n';const offsets=[0];objs.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(pdf,'ascii')}
function svgPreview(doc,src,index){const lines=[];for(const b of plainBlocks(src))for(const l of wrap(b.text.replace(/^#+\s*/,''),78))lines.push(l);let tspans=lines.slice(0,48).map((l,i)=>`<text x="${index?65:90}" y="${150+i*18}" font-size="12">${xmlEsc(l)}</text>`).join('');return `<svg xmlns="http://www.w3.org/2000/svg" width="816" height="1056" viewBox="0 0 612 792"><rect width="612" height="792" fill="white"/><rect x="${index?12:579}" y="34" width="21" height="724" fill="#a64618"/><text x="${index?65:90}" y="70" font-family="Arial" font-size="8" font-weight="bold" fill="#a64618">LA HABRA HEIGHTS FIRE WATCH · ${xmlEsc(doc.code)} · ${xmlEsc(doc.status.toUpperCase())}</text><text x="${index?65:90}" y="110" font-family="Arial" font-size="25" font-weight="bold" fill="#202b32">${xmlEsc(index?doc.title+' — continued':doc.title)}</text><g font-family="Arial" fill="#202b32">${tspans}</g><line x1="${index?65:90}" y1="750" x2="560" y2="750" stroke="#aeb8bd"/><text x="${index?65:90}" y="770" font-family="Arial" font-size="8">${xmlEsc(doc.code)} · Reviewed ${xmlEsc(doc.lastReviewed)} · ${index+1} of ${doc.pageCount}</text></svg>`}
const files=(await walk(path.join(root,'handouts'))).filter(f=>f.endsWith('.md')).sort(),docs=[],codes=new Set();for(const file of files){const {data:d,content}=frontMatter(await fs.readFile(file,'utf8'),path.relative(root,file));for(const k of required)if(d[k]===undefined||d[k]==='')throw Error(`${file}: missing metadata '${k}'`);if(codes.has(d.code))throw Error(`duplicate code ${d.code}`);codes.add(d.code);if(!sections.includes(d.section)||d.sectionNumber!==sections.indexOf(d.section)+1)throw Error(`${d.code}: invalid section metadata`);if(!statuses.includes(d.status))throw Error(`${d.code}: invalid status`);const chunks=content.split(/\n<!--\s*pagebreak\s*-->\n/i);if(![1,2].includes(d.pageCount)||chunks.length!==d.pageCount)throw Error(`${d.code}: wrong page count`);if(!d.reviewers.editor||!d.reviewers.subjectMatter||!d.sources.length)throw Error(`${d.code}: incomplete review/source metadata`);docs.push({meta:d,chunks})}
await fs.rm(path.join(root,'build'),{recursive:true,force:true});for(const d of ['build/html','build/assets','docs/pdfs','docs/previews'])await fs.mkdir(path.join(root,d),{recursive:true});await fs.copyFile(path.join(root,'assets/styles/print.css'),path.join(root,'build/assets/print.css'));const tpl=await fs.readFile(path.join(root,'templates/handout.html'),'utf8');for(const {meta:m,chunks} of docs){const pages=chunks.map((c,i)=>`<article class="sheet ${i?'back':'front'}"><div class="edge">${esc(m.section.toUpperCase())} · ${String(m.sectionNumber).padStart(2,'0')}</div><main class="content"><header class="kicker">La Habra Heights Fire Watch · Emergency Preparedness Binder <span class="status">${esc(m.status.toUpperCase())}</span></header><h1>${esc(i?m.title+' — continued':m.title)}</h1>${markdown(c)}<footer class="footer"><span>${m.code} · v${m.version}</span><span>Last reviewed: ${m.lastReviewed}</span><span>${i+1} of ${m.pageCount}</span></footer></main></article>`).join('');const html=tpl.replace('{{title}}',esc(m.title)).replace('{{cssPath}}','../assets/print.css').replace('{{pages}}',pages);for(const x of html.matchAll(/(?:href|src)="([^"]+)"/g)){if(/^(https?:|#|mailto:|data:)/.test(x[1]))continue;try{await fs.access(path.resolve(root,'build/html',x[1]))}catch{throw Error(`${m.code}: broken local link ${x[1]}`)}}await fs.writeFile(path.join(root,'build/html',m.code+'.html'),html);const pdf=makePdf(m,chunks);await fs.writeFile(path.join(root,'docs/pdfs',m.code+'.pdf'),pdf);const count=(pdf.toString('ascii').match(/\/Type \/Page\b/g)||[]).length;if(count!==m.pageCount)throw Error(`${m.code}: PDF page count ${count}, expected ${m.pageCount}`);for(let i=0;i<chunks.length;i++)await fs.writeFile(path.join(root,'docs/previews',`${m.code}-page-${i+1}.svg`),svgPreview(m,chunks[i],i))}
const groups=sections.map((s,i)=>`## ${i+1}. ${s}\n\n| Code | Title | Status | Version | Last reviewed | Pages |\n|---|---|---|---|---|---:|\n`+(docs.filter(d=>d.meta.section===s).map(d=>`| ${d.meta.code} | ${d.meta.title} | ${d.meta.status} | ${d.meta.version} | ${d.meta.lastReviewed} | ${d.meta.pageCount} |`).join('\n')||'| — | _No handouts yet_ | — | — | — | — |')).join('\n\n');await fs.writeFile(path.join(root,'BINDER_INDEX.md'),`# Binder index\n\nGenerated by \`npm run build\`. Only approved documents may be published to Moodle.\n\n${groups}\n`);const approved=docs.filter(d=>d.meta.status==='approved');await fs.writeFile(path.join(root,'docs/moodle-index.html'),'<!-- Generated; approved handouts only. Replace PDF_URL after Moodle upload. -->\n<div class="lhhfw-binder"><h1>Emergency Preparedness Binder</h1>'+sections.map(s=>`<section><h2>${esc(s)}</h2>${approved.some(d=>d.meta.section===s)?'<ul>'+approved.filter(d=>d.meta.section===s).map(d=>`<li><a href="PDF_URL/${d.meta.code}.pdf">${esc(d.meta.title)}</a> (${d.meta.code}, reviewed ${d.meta.lastReviewed})</li>`).join('')+'</ul>':'<p><em>No approved handouts currently published.</em></p>'}</section>`).join('')+'</div>\n');console.log(`Built and checked ${docs.length} handouts / ${docs.reduce((n,d)=>n+d.meta.pageCount,0)} PDF pages.`)
